services:
  db:
    container_name: karaoke_database
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
